from enum import StrEnum


class ApprovalState(StrEnum):
    DRAFT = "DRAFT"
    DOCUMENTS_INCOMPLETE = "DOCUMENTS_INCOMPLETE"
    EXTRACTION_IN_PROGRESS = "EXTRACTION_IN_PROGRESS"
    EXTRACTION_REVIEW = "EXTRACTION_REVIEW"
    BOQ_IN_PROGRESS = "BOQ_IN_PROGRESS"
    BOQ_REVIEW = "BOQ_REVIEW"
    PRICING_IN_PROGRESS = "PRICING_IN_PROGRESS"
    RFQ_REQUIRED = "RFQ_REQUIRED"
    CALCULATION_IN_PROGRESS = "CALCULATION_IN_PROGRESS"
    INDEPENDENT_VALIDATION = "INDEPENDENT_VALIDATION"
    EXPERT_REVIEW = "EXPERT_REVIEW"
    BLOCKED = "BLOCKED"
    APPROVED_FOR_INTERNAL_USE = "APPROVED_FOR_INTERNAL_USE"
    APPROVED_FOR_BID = "APPROVED_FOR_BID"
    SUPERSEDED = "SUPERSEDED"
    ARCHIVED = "ARCHIVED"


class Severity(StrEnum):
    INFO = "INFO"
    WARNING = "WARNING"
    BLOCKER = "BLOCKER"


class VerificationStatus(StrEnum):
    UNVERIFIED = "UNVERIFIED"
    IN_REVIEW = "IN_REVIEW"
    VERIFIED = "VERIFIED"
    REJECTED = "REJECTED"
    CONFLICT = "CONFLICT"


class VersionStatus(StrEnum):
    DRAFT = "DRAFT"
    APPROVED = "APPROVED"
    SUPERSEDED = "SUPERSEDED"
    REVOKED = "REVOKED"


class EvidenceMethod(StrEnum):
    FILE_METADATA = "FILE_METADATA"
    NATIVE_PARSER = "NATIVE_PARSER"
    FORMULA_EVALUATION = "FORMULA_EVALUATION"
    TABLE_PARSER = "TABLE_PARSER"
    VISUAL_MODEL = "VISUAL_MODEL"
    OCR = "OCR"
    RULE_ENGINE = "RULE_ENGINE"
    EXTERNAL_SYSTEM = "EXTERNAL_SYSTEM"
    MANUAL = "MANUAL"


class MatchClass(StrEnum):
    EXACT = "EXACT"
    FUNCTIONAL_ANALOGUE = "FUNCTIONAL_ANALOGUE"
    CONDITIONALLY_ACCEPTABLE_ANALOGUE = "CONDITIONALLY_ACCEPTABLE_ANALOGUE"
    TECHNICALLY_UNACCEPTABLE = "TECHNICALLY_UNACCEPTABLE"
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"


class PriceEvidenceClass(StrEnum):
    OFFICIAL_OR_PRIMARY = "OFFICIAL_OR_PRIMARY"
    INDEPENDENT_MARKET = "INDEPENDENT_MARKET"
    INTERNAL_HISTORY = "INTERNAL_HISTORY"
    COMMERCIAL_QUOTE = "COMMERCIAL_QUOTE"


class PriceStatus(StrEnum):
    UNNORMALIZED = "UNNORMALIZED"
    NORMALIZED = "NORMALIZED"
    VERIFIED = "VERIFIED"
    RFQ_REQUIRED = "RFQ_REQUIRED"
    EXPERT_REVIEW_REQUIRED = "EXPERT_REVIEW_REQUIRED"
    EXPIRED = "EXPIRED"
    REJECTED = "REJECTED"


class VatBasis(StrEnum):
    EXCLUSIVE = "EXCLUSIVE"
    INCLUSIVE = "INCLUSIVE"
    NOT_APPLICABLE = "NOT_APPLICABLE"


class CostCategory(StrEnum):
    LABOUR = "LABOUR"
    PLANT = "PLANT"
    MATERIAL = "MATERIAL"
    SUBCONTRACT = "SUBCONTRACT"
    LOGISTICS = "LOGISTICS"
    MOBILISATION = "MOBILISATION"
    CONTRACT_FINANCE = "CONTRACT_FINANCE"
    RISK = "RISK"
    OVERHEAD = "OVERHEAD"
    PROFIT = "PROFIT"
    TAX = "TAX"


class CostBasisKind(StrEnum):
    MARKET = "MARKET"
    NORMATIVE = "NORMATIVE"
    APPROVED_ASSUMPTION = "APPROVED_ASSUMPTION"
    RISK_MODEL = "RISK_MODEL"


class ActorRole(StrEnum):
    ESTIMATOR = "ESTIMATOR"
    PROCUREMENT = "PROCUREMENT"
    TECHNICAL_EXPERT = "TECHNICAL_EXPERT"
    REVIEWER = "REVIEWER"
    APPROVER = "APPROVER"
    METHODOLOGY_OWNER = "METHODOLOGY_OWNER"
    CATALOG_OWNER = "CATALOG_OWNER"
    AUDITOR = "AUDITOR"
    ADMIN = "ADMIN"
    SYSTEM = "SYSTEM"


class ProjectAccessLevel(StrEnum):
    MEMBER = "MEMBER"
    OWNER = "OWNER"


class ProjectMembershipStatus(StrEnum):
    ACTIVE = "ACTIVE"
    REVOKED = "REVOKED"


class ApprovalDecision(StrEnum):
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    CHANGES_REQUESTED = "CHANGES_REQUESTED"


class FindingCode(StrEnum):
    CURRENT_DOCUMENT_SET_NOT_CONFIRMED = "CURRENT_DOCUMENT_SET_NOT_CONFIRMED"
    CRITICAL_DOCUMENT_MISSING = "CRITICAL_DOCUMENT_MISSING"
    KEY_QUANTITY_UNVERIFIED = "KEY_QUANTITY_UNVERIFIED"
    UNRESOLVED_CONFLICT = "UNRESOLVED_CONFLICT"
    COST_WITHOUT_BASIS = "COST_WITHOUT_BASIS"
    TECHNICAL_ANALOGUE_UNVERIFIED = "TECHNICAL_ANALOGUE_UNVERIFIED"
    PRICE_NORMALIZATION_FAILED = "PRICE_NORMALIZATION_FAILED"
    INDEPENDENT_VALIDATION_MISSING = "INDEPENDENT_VALIDATION_MISSING"
    INDEPENDENT_RECALCULATION_MISMATCH = "INDEPENDENT_RECALCULATION_MISMATCH"
    UNVERIFIED_COST_THRESHOLD_UNCONFIGURED = "UNVERIFIED_COST_THRESHOLD_UNCONFIGURED"
    UNVERIFIED_COST_SHARE_EXCEEDED = "UNVERIFIED_COST_SHARE_EXCEEDED"
    REQUIRED_APPROVAL_MISSING = "REQUIRED_APPROVAL_MISSING"
    CONTROLLED_VERSION_MISSING = "CONTROLLED_VERSION_MISSING"
    CONTROLLED_VERSION_NOT_APPROVED = "CONTROLLED_VERSION_NOT_APPROVED"
    CALCULATION_SNAPSHOT_MISSING = "CALCULATION_SNAPSHOT_MISSING"
    CALCULATION_SNAPSHOT_STALE = "CALCULATION_SNAPSHOT_STALE"
    CALCULATION_SNAPSHOT_INTEGRITY_FAILED = "CALCULATION_SNAPSHOT_INTEGRITY_FAILED"
    CRITICAL_MANUAL_CHANGE_NOT_APPROVED = "CRITICAL_MANUAL_CHANGE_NOT_APPROVED"
    FOUR_EYES_VIOLATION = "FOUR_EYES_VIOLATION"
    CONTRACT_RISK_UNRESOLVED = "CONTRACT_RISK_UNRESOLVED"
    BLOCKING_CONTOUR_FINDING = "BLOCKING_CONTOUR_FINDING"
    NORMATIVE_ENGINE_UNAVAILABLE = "NORMATIVE_ENGINE_UNAVAILABLE"
    NORMATIVE_CALCULATION_MISSING = "NORMATIVE_CALCULATION_MISSING"
    PRODUCTION_QUALIFICATION_INCOMPLETE = "PRODUCTION_QUALIFICATION_INCOMPLETE"
    OPERATIONAL_INTEGRITY_UNAVAILABLE = "OPERATIONAL_INTEGRITY_UNAVAILABLE"
    QUANTITY_FORMULA_MISMATCH = "QUANTITY_FORMULA_MISMATCH"
    QUANTITY_UNIT_MISMATCH = "QUANTITY_UNIT_MISMATCH"
    QUANTITY_BALANCE_MISMATCH = "QUANTITY_BALANCE_MISMATCH"
    QUANTITY_HISTORICAL_OUTLIER = "QUANTITY_HISTORICAL_OUTLIER"
    QUANTITY_THRESHOLD_UNCONFIGURED = "QUANTITY_THRESHOLD_UNCONFIGURED"
    QUANTITY_SIGN_INVALID = "QUANTITY_SIGN_INVALID"
    PROJECT_PASSPORT_INCOMPLETE = "PROJECT_PASSPORT_INCOMPLETE"
    CONTRACT_TERM_MISSING = "CONTRACT_TERM_MISSING"
    CONTRACT_COST_IMPACT_UNRESOLVED = "CONTRACT_COST_IMPACT_UNRESOLVED"
    ACTUAL_NOT_VERIFIED = "ACTUAL_NOT_VERIFIED"
    DOCUMENT_REFERENCE_MISSING = "DOCUMENT_REFERENCE_MISSING"
    DOCUMENT_REVISION_AMBIGUOUS = "DOCUMENT_REVISION_AMBIGUOUS"
    DOCUMENT_GRAPH_CYCLE = "DOCUMENT_GRAPH_CYCLE"
    DOCUMENT_IDENTITY_MISMATCH = "DOCUMENT_IDENTITY_MISMATCH"
    APPROVAL_THRESHOLD_UNCONFIGURED = "APPROVAL_THRESHOLD_UNCONFIGURED"
    RISK_MODEL_INCOMPLETE = "RISK_MODEL_INCOMPLETE"


class QuantityOperation(StrEnum):
    SUM = "SUM"
    PRODUCT = "PRODUCT"
    RECTANGULAR_VOLUME = "RECTANGULAR_VOLUME"
    CYLINDER_VOLUME = "CYLINDER_VOLUME"


class ContractTermKind(StrEnum):
    COMPLETION_DATES = "COMPLETION_DATES"
    PHASING = "PHASING"
    PENALTIES = "PENALTIES"
    RETENTION = "RETENTION"
    BID_OR_PERFORMANCE_SECURITY = "BID_OR_PERFORMANCE_SECURITY"
    BANK_GUARANTEE = "BANK_GUARANTEE"
    ADVANCE = "ADVANCE"
    PAYMENT_DEFERRAL = "PAYMENT_DEFERRAL"
    WARRANTY = "WARRANTY"
    FIXED_PRICE = "FIXED_PRICE"
    CURRENCY_RISK = "CURRENCY_RISK"
    DESIGN_ERROR_LIABILITY = "DESIGN_ERROR_LIABILITY"
    MOBILISATION = "MOBILISATION"
    DOCUMENTATION = "DOCUMENTATION"
    INDEXATION_LIMITS = "INDEXATION_LIMITS"
    ACCEPTANCE_PROCEDURE = "ACCEPTANCE_PROCEDURE"


class VarianceReason(StrEnum):
    SCOPE_CHANGE = "SCOPE_CHANGE"
    QUANTITY_ERROR = "QUANTITY_ERROR"
    PRICE_CHANGE = "PRICE_CHANGE"
    SUPPLIER_CHANGE = "SUPPLIER_CHANGE"
    PRODUCTIVITY_VARIANCE = "PRODUCTIVITY_VARIANCE"
    LOGISTICS_VARIANCE = "LOGISTICS_VARIANCE"
    SCHEDULE_VARIANCE = "SCHEDULE_VARIANCE"
    RISK_REALISED = "RISK_REALISED"
    DATA_QUALITY = "DATA_QUALITY"
    METHODOLOGY_ERROR = "METHODOLOGY_ERROR"
    OTHER_APPROVED = "OTHER_APPROVED"


class ApprovalReason(StrEnum):
    HIGH_VALUE = "HIGH_VALUE"
    UNVERIFIED_QUANTITY = "UNVERIFIED_QUANTITY"
    NONSTANDARD_WORK = "NONSTANDARD_WORK"
    COMPLEX_EQUIPMENT = "COMPLEX_EQUIPMENT"
    TECHNICAL_ANALOGUE = "TECHNICAL_ANALOGUE"
    RFQ_PRICE = "RFQ_PRICE"
    HIGH_PRICE_SPREAD = "HIGH_PRICE_SPREAD"
    DOCUMENT_CONFLICT = "DOCUMENT_CONFLICT"
    MANUAL_COEFFICIENT = "MANUAL_COEFFICIENT"
    LARGE_RESERVE = "LARGE_RESERVE"
    MATERIAL_PROFIT_IMPACT = "MATERIAL_PROFIT_IMPACT"
    CONTRACT_COST_IMPACT = "CONTRACT_COST_IMPACT"
