"""add business verification contours

Revision ID: 797ef0df3ed1
Revises: fc826e4d27af
Create Date: 2026-07-23 14:10:39.946938
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "797ef0df3ed1"
down_revision: str | None = "fc826e4d27af"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "adapter_qualifications",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("adapter_name", sa.String(length=200), nullable=False),
        sa.Column("adapter_version", sa.String(length=200), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("valid_until", sa.Date(), nullable=True),
        sa.Column("test_evidence_hash", sa.String(length=64), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("approved_by", sa.String(length=128), nullable=False),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("adapter_name", "adapter_version"),
    )
    op.create_index(
        op.f("ix_adapter_qualifications_status"), "adapter_qualifications", ["status"], unique=False
    )
    op.create_table(
        "contract_terms",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("project_id", sa.String(length=64), nullable=False),
        sa.Column("kind", sa.String(length=100), nullable=False),
        sa.Column("verified", sa.Boolean(), nullable=False),
        sa.Column("cost_impact_resolved", sa.Boolean(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "kind"),
    )
    op.create_index(
        op.f("ix_contract_terms_cost_impact_resolved"),
        "contract_terms",
        ["cost_impact_resolved"],
        unique=False,
    )
    op.create_index(op.f("ix_contract_terms_kind"), "contract_terms", ["kind"], unique=False)
    op.create_index(
        op.f("ix_contract_terms_project_id"), "contract_terms", ["project_id"], unique=False
    )
    op.create_table(
        "normative_calculations",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("project_id", sa.String(length=64), nullable=False),
        sa.Column("adapter_qualification_id", sa.String(length=128), nullable=False),
        sa.Column("normative_basis_version", sa.String(length=200), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("total", sa.Numeric(precision=38, scale=12), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("artifact_hash", sa.String(length=64), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["adapter_qualification_id"],
            ["adapter_qualifications.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_normative_calculations_project_id"),
        "normative_calculations",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_normative_calculations_status"), "normative_calculations", ["status"], unique=False
    )
    op.create_table(
        "project_passport_facts",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("project_id", sa.String(length=64), nullable=False),
        sa.Column("field_name", sa.String(length=200), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "field_name"),
    )
    op.create_index(
        op.f("ix_project_passport_facts_project_id"),
        "project_passport_facts",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_passport_facts_status"), "project_passport_facts", ["status"], unique=False
    )
    op.create_table(
        "risk_items",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("project_id", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("expected_impact", sa.Numeric(precision=38, scale=12), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_risk_items_project_id"), "risk_items", ["project_id"], unique=False)
    op.create_index(op.f("ix_risk_items_status"), "risk_items", ["status"], unique=False)
    op.create_table(
        "scenario_runs",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("project_id", sa.String(length=64), nullable=False),
        sa.Column("base_calculation_run_id", sa.String(length=64), nullable=False),
        sa.Column("scenario_version", sa.String(length=200), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("grand_total", sa.Numeric(precision=38, scale=12), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["base_calculation_run_id"],
            ["calculation_runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_scenario_runs_project_id"), "scenario_runs", ["project_id"], unique=False
    )
    op.create_table(
        "export_artifacts",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("project_id", sa.String(length=64), nullable=False),
        sa.Column("snapshot_id", sa.String(length=64), nullable=False),
        sa.Column("adapter_qualification_id", sa.String(length=128), nullable=False),
        sa.Column("format", sa.String(length=80), nullable=False),
        sa.Column("object_hash", sa.String(length=64), nullable=False),
        sa.Column("object_key", sa.String(length=1000), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["adapter_qualification_id"],
            ["adapter_qualifications.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["calculation_snapshots.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_export_artifacts_project_id"), "export_artifacts", ["project_id"], unique=False
    )
    op.create_table(
        "extraction_runs",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("project_id", sa.String(length=64), nullable=False),
        sa.Column("document_revision_id", sa.String(length=64), nullable=False),
        sa.Column("adapter_qualification_id", sa.String(length=128), nullable=False),
        sa.Column("method", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["adapter_qualification_id"],
            ["adapter_qualifications.id"],
        ),
        sa.ForeignKeyConstraint(
            ["document_revision_id"],
            ["document_revisions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_extraction_runs_document_revision_id"),
        "extraction_runs",
        ["document_revision_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_extraction_runs_project_id"), "extraction_runs", ["project_id"], unique=False
    )
    op.create_index(op.f("ix_extraction_runs_status"), "extraction_runs", ["status"], unique=False)
    op.create_table(
        "variance_records",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("project_id", sa.String(length=64), nullable=False),
        sa.Column("actual_record_id", sa.String(length=64), nullable=False),
        sa.Column("snapshot_id", sa.String(length=64), nullable=False),
        sa.Column("metric", sa.String(length=100), nullable=False),
        sa.Column("reason", sa.String(length=100), nullable=False),
        sa.Column("absolute_variance", sa.Numeric(precision=38, scale=12), nullable=False),
        sa.Column("relative_variance", sa.Numeric(precision=38, scale=12), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("classified_by", sa.String(length=128), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["actual_record_id"],
            ["actual_records.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["calculation_snapshots.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("actual_record_id"),
    )
    op.create_index(
        op.f("ix_variance_records_metric"), "variance_records", ["metric"], unique=False
    )
    op.create_index(
        op.f("ix_variance_records_project_id"), "variance_records", ["project_id"], unique=False
    )
    op.create_index(
        op.f("ix_variance_records_reason"), "variance_records", ["reason"], unique=False
    )
    op.create_table(
        "calibration_examples",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("project_id", sa.String(length=64), nullable=False),
        sa.Column("actual_record_id", sa.String(length=64), nullable=False),
        sa.Column("variance_record_id", sa.String(length=64), nullable=False),
        sa.Column("features_snapshot_id", sa.String(length=64), nullable=False),
        sa.Column("metric", sa.String(length=100), nullable=False),
        sa.Column("target_value", sa.Numeric(precision=38, scale=12), nullable=False),
        sa.Column("unit", sa.String(length=64), nullable=False),
        sa.Column("approved", sa.Boolean(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["actual_record_id"],
            ["actual_records.id"],
        ),
        sa.ForeignKeyConstraint(
            ["features_snapshot_id"],
            ["calculation_snapshots.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["variance_record_id"],
            ["variance_records.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("actual_record_id"),
        sa.UniqueConstraint("variance_record_id"),
    )
    op.create_index(
        op.f("ix_calibration_examples_approved"), "calibration_examples", ["approved"], unique=False
    )
    op.create_index(
        op.f("ix_calibration_examples_metric"), "calibration_examples", ["metric"], unique=False
    )
    op.create_index(
        op.f("ix_calibration_examples_project_id"),
        "calibration_examples",
        ["project_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_calibration_examples_project_id"), table_name="calibration_examples")
    op.drop_index(op.f("ix_calibration_examples_metric"), table_name="calibration_examples")
    op.drop_index(op.f("ix_calibration_examples_approved"), table_name="calibration_examples")
    op.drop_table("calibration_examples")
    op.drop_index(op.f("ix_variance_records_reason"), table_name="variance_records")
    op.drop_index(op.f("ix_variance_records_project_id"), table_name="variance_records")
    op.drop_index(op.f("ix_variance_records_metric"), table_name="variance_records")
    op.drop_table("variance_records")
    op.drop_index(op.f("ix_extraction_runs_status"), table_name="extraction_runs")
    op.drop_index(op.f("ix_extraction_runs_project_id"), table_name="extraction_runs")
    op.drop_index(op.f("ix_extraction_runs_document_revision_id"), table_name="extraction_runs")
    op.drop_table("extraction_runs")
    op.drop_index(op.f("ix_export_artifacts_project_id"), table_name="export_artifacts")
    op.drop_table("export_artifacts")
    op.drop_index(op.f("ix_scenario_runs_project_id"), table_name="scenario_runs")
    op.drop_table("scenario_runs")
    op.drop_index(op.f("ix_risk_items_status"), table_name="risk_items")
    op.drop_index(op.f("ix_risk_items_project_id"), table_name="risk_items")
    op.drop_table("risk_items")
    op.drop_index(op.f("ix_project_passport_facts_status"), table_name="project_passport_facts")
    op.drop_index(op.f("ix_project_passport_facts_project_id"), table_name="project_passport_facts")
    op.drop_table("project_passport_facts")
    op.drop_index(op.f("ix_normative_calculations_status"), table_name="normative_calculations")
    op.drop_index(op.f("ix_normative_calculations_project_id"), table_name="normative_calculations")
    op.drop_table("normative_calculations")
    op.drop_index(op.f("ix_contract_terms_project_id"), table_name="contract_terms")
    op.drop_index(op.f("ix_contract_terms_kind"), table_name="contract_terms")
    op.drop_index(op.f("ix_contract_terms_cost_impact_resolved"), table_name="contract_terms")
    op.drop_table("contract_terms")
    op.drop_index(op.f("ix_adapter_qualifications_status"), table_name="adapter_qualifications")
    op.drop_table("adapter_qualifications")
    # ### end Alembic commands ###
