"""initial safety-critical schema

Revision ID: fc826e4d27af
Revises:
Create Date: 2026-07-23 13:52:47.531769
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "fc826e4d27af"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_events",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("aggregate_type", sa.String(length=100), nullable=False),
        sa.Column("aggregate_id", sa.String(length=128), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("actor_id", sa.String(length=128), nullable=False),
        sa.Column("actor_roles", sa.JSON(), nullable=False),
        sa.Column("request_id", sa.String(length=128), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("previous_hash", sa.String(length=64), nullable=False),
        sa.Column("event_hash", sa.String(length=64), nullable=False),
        sa.Column("signature", sa.String(length=64), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("aggregate_type", "aggregate_id", "sequence"),
        sa.UniqueConstraint("event_hash"),
    )
    op.create_index(
        "ix_audit_aggregate_sequence",
        "audit_events",
        ["aggregate_type", "aggregate_id", "sequence"],
        unique=False,
    )
    op.create_table(
        "controlled_versions",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("kind", sa.String(length=100), nullable=False),
        sa.Column("version_label", sa.String(length=200), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("approved_by", sa.String(length=128), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("kind", "version_label"),
    )
    op.create_index(
        op.f("ix_controlled_versions_kind"), "controlled_versions", ["kind"], unique=False
    )
    op.create_table(
        "outbox_events",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("topic", sa.String(length=200), nullable=False),
        sa.Column("aggregate_id", sa.String(length=128), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_outbox_events_topic"), "outbox_events", ["topic"], unique=False)
    op.create_table(
        "projects",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("organization_id", sa.String(length=64), nullable=False),
        sa.Column("code", sa.String(length=128), nullable=False),
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("state", sa.String(length=64), nullable=False),
        sa.Column("blocked_resume_state", sa.String(length=64), nullable=True),
        sa.Column("current_document_set_revision_id", sa.String(length=64), nullable=True),
        sa.Column("row_version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "code"),
    )
    op.create_index(
        op.f("ix_projects_organization_id"), "projects", ["organization_id"], unique=False
    )
    op.create_table(
        "approval_tasks",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("project_id", sa.String(length=64), nullable=False),
        sa.Column("task_type", sa.String(length=100), nullable=False),
        sa.Column("entity_type", sa.String(length=100), nullable=False),
        sa.Column("entity_id", sa.String(length=128), nullable=False),
        sa.Column("assigned_role", sa.String(length=80), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("required", sa.Boolean(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_approval_tasks_project_id"), "approval_tasks", ["project_id"], unique=False
    )
    op.create_index(op.f("ix_approval_tasks_status"), "approval_tasks", ["status"], unique=False)
    op.create_table(
        "boq_lines",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("project_id", sa.String(length=64), nullable=False),
        sa.Column("wbs_node_id", sa.String(length=128), nullable=False),
        sa.Column("work_code", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("unit", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_boq_lines_project_id"), "boq_lines", ["project_id"], unique=False)
    op.create_index(op.f("ix_boq_lines_wbs_node_id"), "boq_lines", ["wbs_node_id"], unique=False)
    op.create_index(op.f("ix_boq_lines_work_code"), "boq_lines", ["work_code"], unique=False)
    op.create_table(
        "calculation_runs",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("project_id", sa.String(length=64), nullable=False),
        sa.Column("engine_version", sa.String(length=200), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("grand_total", sa.Numeric(precision=38, scale=12), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_calculation_runs_project_id"), "calculation_runs", ["project_id"], unique=False
    )
    op.create_table(
        "conflicts",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("project_id", sa.String(length=64), nullable=False),
        sa.Column("field_name", sa.String(length=300), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_conflicts_project_id"), "conflicts", ["project_id"], unique=False)
    op.create_index(op.f("ix_conflicts_status"), "conflicts", ["status"], unique=False)
    op.create_table(
        "documents",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("project_id", sa.String(length=64), nullable=False),
        sa.Column("logical_key", sa.String(length=300), nullable=False),
        sa.Column("title", sa.String(length=1000), nullable=False),
        sa.Column("document_type", sa.String(length=100), nullable=False),
        sa.Column("critical", sa.Boolean(), nullable=False),
        sa.Column("cancelled", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "logical_key"),
    )
    op.create_index(op.f("ix_documents_project_id"), "documents", ["project_id"], unique=False)
    op.create_table(
        "manual_changes",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("project_id", sa.String(length=64), nullable=False),
        sa.Column("entity_type", sa.String(length=100), nullable=False),
        sa.Column("entity_id", sa.String(length=128), nullable=False),
        sa.Column("field_name", sa.String(length=200), nullable=False),
        sa.Column("critical", sa.Boolean(), nullable=False),
        sa.Column("changed_by", sa.String(length=128), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("changed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_manual_changes_critical"), "manual_changes", ["critical"], unique=False
    )
    op.create_index(
        op.f("ix_manual_changes_project_id"), "manual_changes", ["project_id"], unique=False
    )
    op.create_table(
        "nomenclature_matches",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("project_id", sa.String(length=64), nullable=False),
        sa.Column("source_item_id", sa.String(length=128), nullable=False),
        sa.Column("canonical_item_id", sa.String(length=128), nullable=True),
        sa.Column("match_class", sa.String(length=80), nullable=False),
        sa.Column("catalog_version_id", sa.String(length=64), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["catalog_version_id"],
            ["controlled_versions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_nomenclature_matches_match_class"),
        "nomenclature_matches",
        ["match_class"],
        unique=False,
    )
    op.create_index(
        op.f("ix_nomenclature_matches_project_id"),
        "nomenclature_matches",
        ["project_id"],
        unique=False,
    )
    op.create_table(
        "price_quotes",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("project_id", sa.String(length=64), nullable=False),
        sa.Column("item_id", sa.String(length=128), nullable=False),
        sa.Column("status", sa.String(length=80), nullable=False),
        sa.Column("quote_date", sa.Date(), nullable=False),
        sa.Column("valid_until", sa.Date(), nullable=True),
        sa.Column("amount", sa.Numeric(precision=38, scale=12), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_price_quotes_item_id"), "price_quotes", ["item_id"], unique=False)
    op.create_index(
        op.f("ix_price_quotes_project_id"), "price_quotes", ["project_id"], unique=False
    )
    op.create_index(op.f("ix_price_quotes_status"), "price_quotes", ["status"], unique=False)
    op.create_table(
        "project_controlled_versions",
        sa.Column("project_id", sa.String(length=64), nullable=False),
        sa.Column("controlled_version_id", sa.String(length=64), nullable=False),
        sa.Column("purpose", sa.String(length=100), nullable=False),
        sa.Column("bound_by", sa.String(length=128), nullable=False),
        sa.Column("bound_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["controlled_version_id"],
            ["controlled_versions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("project_id", "controlled_version_id"),
        sa.UniqueConstraint("project_id", "purpose"),
    )
    op.create_table(
        "scope_findings",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("project_id", sa.String(length=64), nullable=False),
        sa.Column("rule_id", sa.String(length=128), nullable=False),
        sa.Column("severity", sa.String(length=30), nullable=False),
        sa.Column("resolved", sa.Boolean(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_scope_findings_project_id"), "scope_findings", ["project_id"], unique=False
    )
    op.create_index(
        op.f("ix_scope_findings_resolved"), "scope_findings", ["resolved"], unique=False
    )
    op.create_table(
        "verification_findings",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("project_id", sa.String(length=64), nullable=False),
        sa.Column("contour", sa.String(length=100), nullable=False),
        sa.Column("code", sa.String(length=150), nullable=False),
        sa.Column("severity", sa.String(length=30), nullable=False),
        sa.Column("resolved", sa.Boolean(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_verification_findings_code"), "verification_findings", ["code"], unique=False
    )
    op.create_index(
        op.f("ix_verification_findings_contour"), "verification_findings", ["contour"], unique=False
    )
    op.create_index(
        op.f("ix_verification_findings_project_id"),
        "verification_findings",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_verification_findings_resolved"),
        "verification_findings",
        ["resolved"],
        unique=False,
    )
    op.create_table(
        "workflow_transitions",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("project_id", sa.String(length=64), nullable=False),
        sa.Column("from_state", sa.String(length=64), nullable=False),
        sa.Column("to_state", sa.String(length=64), nullable=False),
        sa.Column("actor_id", sa.String(length=128), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_workflow_transitions_project_id"),
        "workflow_transitions",
        ["project_id"],
        unique=False,
    )
    op.create_table(
        "approval_records",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("task_id", sa.String(length=64), nullable=False),
        sa.Column("decision", sa.String(length=50), nullable=False),
        sa.Column("decided_by", sa.String(length=128), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["approval_tasks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_approval_records_task_id"), "approval_records", ["task_id"], unique=False
    )
    op.create_table(
        "atomic_cost_inputs",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("project_id", sa.String(length=64), nullable=False),
        sa.Column("calculation_run_id", sa.String(length=64), nullable=True),
        sa.Column("semantic_key", sa.String(length=300), nullable=False),
        sa.Column("category", sa.String(length=80), nullable=False),
        sa.Column("amount_basis_id", sa.String(length=128), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["calculation_run_id"],
            ["calculation_runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_atomic_cost_inputs_calculation_run_id"),
        "atomic_cost_inputs",
        ["calculation_run_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_atomic_cost_inputs_project_id"), "atomic_cost_inputs", ["project_id"], unique=False
    )
    op.create_table(
        "calculation_snapshots",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("project_id", sa.String(length=64), nullable=False),
        sa.Column("calculation_run_id", sa.String(length=64), nullable=False),
        sa.Column("document_set_revision_id", sa.String(length=64), nullable=False),
        sa.Column("input_hash", sa.String(length=64), nullable=False),
        sa.Column("output_hash", sa.String(length=64), nullable=False),
        sa.Column("snapshot_hash", sa.String(length=64), nullable=False),
        sa.Column("fixed", sa.Boolean(), nullable=False),
        sa.Column("object_key", sa.String(length=1000), nullable=False),
        sa.Column("created_by", sa.String(length=128), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["calculation_run_id"],
            ["calculation_runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("calculation_run_id"),
        sa.UniqueConstraint("snapshot_hash"),
    )
    op.create_index(
        op.f("ix_calculation_snapshots_project_id"),
        "calculation_snapshots",
        ["project_id"],
        unique=False,
    )
    op.create_table(
        "document_revisions",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("document_id", sa.String(length=64), nullable=False),
        sa.Column("revision_label", sa.String(length=100), nullable=False),
        sa.Column("issue_date", sa.Date(), nullable=True),
        sa.Column("object_hash", sa.String(length=64), nullable=False),
        sa.Column("object_key", sa.String(length=1000), nullable=False),
        sa.Column("original_filename", sa.String(length=1000), nullable=False),
        sa.Column("media_type", sa.String(length=200), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("supersedes_revision_id", sa.String(length=64), nullable=True),
        sa.Column("is_current", sa.Boolean(), nullable=False),
        sa.Column("corrupt", sa.Boolean(), nullable=False),
        sa.Column("protected", sa.Boolean(), nullable=False),
        sa.Column("inspection_payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["supersedes_revision_id"],
            ["document_revisions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("document_id", "revision_label"),
    )
    op.create_index(
        op.f("ix_document_revisions_document_id"),
        "document_revisions",
        ["document_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_document_revisions_object_hash"),
        "document_revisions",
        ["object_hash"],
        unique=False,
    )
    op.create_table(
        "document_set_revisions",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("project_id", sa.String(length=64), nullable=False),
        sa.Column("manifest_hash", sa.String(length=64), nullable=False),
        sa.Column("revision_ids", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("created_by", sa.String(length=128), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("confirmed_by", sa.String(length=128), nullable=True),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "manifest_hash"),
    )
    op.create_index(
        op.f("ix_document_set_revisions_project_id"),
        "document_set_revisions",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_document_set_revisions_status"), "document_set_revisions", ["status"], unique=False
    )
    op.create_table(
        "normalized_prices",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("quote_id", sa.String(length=64), nullable=False),
        sa.Column("amount_per_unit", sa.Numeric(precision=38, scale=12), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("formula_hash", sa.String(length=64), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["quote_id"],
            ["price_quotes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_normalized_prices_quote_id"), "normalized_prices", ["quote_id"], unique=False
    )
    op.create_table(
        "quantities",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("boq_line_id", sa.String(length=64), nullable=False),
        sa.Column("value", sa.Numeric(precision=38, scale=12), nullable=False),
        sa.Column("unit", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["boq_line_id"],
            ["boq_lines.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_quantities_boq_line_id"), "quantities", ["boq_line_id"], unique=False)
    op.create_index(op.f("ix_quantities_status"), "quantities", ["status"], unique=False)
    op.create_table(
        "evidence_observations",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("project_id", sa.String(length=64), nullable=False),
        sa.Column("document_revision_id", sa.String(length=64), nullable=False),
        sa.Column("field_name", sa.String(length=300), nullable=False),
        sa.Column("method", sa.String(length=100), nullable=False),
        sa.Column("method_version", sa.String(length=200), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_revision_id"],
            ["document_revisions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_evidence_observations_document_revision_id"),
        "evidence_observations",
        ["document_revision_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_evidence_observations_field_name"),
        "evidence_observations",
        ["field_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_evidence_observations_project_id"),
        "evidence_observations",
        ["project_id"],
        unique=False,
    )
    op.create_table(
        "file_manifest_entries",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("document_revision_id", sa.String(length=64), nullable=False),
        sa.Column("archive_path", sa.String(length=2000), nullable=False),
        sa.Column("object_hash", sa.String(length=64), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("media_type", sa.String(length=200), nullable=False),
        sa.Column("corrupt", sa.Boolean(), nullable=False),
        sa.Column("protected", sa.Boolean(), nullable=False),
        sa.Column("nested_archive", sa.Boolean(), nullable=False),
        sa.Column("inspection_payload", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_revision_id"],
            ["document_revisions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("document_revision_id", "archive_path"),
    )
    op.create_index(
        op.f("ix_file_manifest_entries_document_revision_id"),
        "file_manifest_entries",
        ["document_revision_id"],
        unique=False,
    )
    op.create_table(
        "release_decisions",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("project_id", sa.String(length=64), nullable=False),
        sa.Column("snapshot_id", sa.String(length=64), nullable=True),
        sa.Column("requested_state", sa.String(length=64), nullable=False),
        sa.Column("resulting_state", sa.String(length=64), nullable=False),
        sa.Column("allowed", sa.Boolean(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("decided_by", sa.String(length=128), nullable=False),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["calculation_snapshots.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_release_decisions_project_id"), "release_decisions", ["project_id"], unique=False
    )
    op.create_table(
        "actual_records",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("project_id", sa.String(length=64), nullable=False),
        sa.Column("entity_type", sa.String(length=100), nullable=False),
        sa.Column("entity_id", sa.String(length=128), nullable=False),
        sa.Column("metric", sa.String(length=100), nullable=False),
        sa.Column("value", sa.Numeric(precision=38, scale=12), nullable=False),
        sa.Column("unit", sa.String(length=64), nullable=False),
        sa.Column("verified", sa.Boolean(), nullable=False),
        sa.Column("source_observation_id", sa.String(length=64), nullable=False),
        sa.Column("occurred_on", sa.Date(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_observation_id"],
            ["evidence_observations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_actual_records_project_id"), "actual_records", ["project_id"], unique=False
    )
    if op.get_bind().dialect.name == "postgresql":
        op.execute(
            """
            CREATE FUNCTION tenderguard_reject_immutable_mutation()
            RETURNS trigger AS $$
            BEGIN
                RAISE EXCEPTION 'immutable TenderGuard record cannot be changed';
            END;
            $$ LANGUAGE plpgsql;
            """
        )
        for table_name in ("audit_events", "evidence_observations"):
            op.execute(
                f"""
                CREATE TRIGGER trg_{table_name}_immutable
                BEFORE UPDATE OR DELETE ON {table_name}
                FOR EACH ROW EXECUTE FUNCTION tenderguard_reject_immutable_mutation();
                """
            )
        op.execute(
            """
            CREATE FUNCTION tenderguard_protect_fixed_snapshot()
            RETURNS trigger AS $$
            BEGIN
                IF OLD.fixed THEN
                    RAISE EXCEPTION 'fixed calculation snapshot cannot be changed';
                END IF;
                IF TG_OP = 'DELETE' THEN
                    RETURN OLD;
                END IF;
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;
            """
        )
        op.execute(
            """
            CREATE TRIGGER trg_calculation_snapshots_fixed
            BEFORE UPDATE OR DELETE ON calculation_snapshots
            FOR EACH ROW EXECUTE FUNCTION tenderguard_protect_fixed_snapshot();
            """
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if op.get_bind().dialect.name == "postgresql":
        op.execute(
            "DROP TRIGGER IF EXISTS trg_calculation_snapshots_fixed ON calculation_snapshots"
        )
        op.execute("DROP FUNCTION IF EXISTS tenderguard_protect_fixed_snapshot()")
        for table_name in ("audit_events", "evidence_observations"):
            op.execute(f"DROP TRIGGER IF EXISTS trg_{table_name}_immutable ON {table_name}")
        op.execute("DROP FUNCTION IF EXISTS tenderguard_reject_immutable_mutation()")
    op.drop_index(op.f("ix_actual_records_project_id"), table_name="actual_records")
    op.drop_table("actual_records")
    op.drop_index(op.f("ix_release_decisions_project_id"), table_name="release_decisions")
    op.drop_table("release_decisions")
    op.drop_index(
        op.f("ix_file_manifest_entries_document_revision_id"), table_name="file_manifest_entries"
    )
    op.drop_table("file_manifest_entries")
    op.drop_index(op.f("ix_evidence_observations_project_id"), table_name="evidence_observations")
    op.drop_index(op.f("ix_evidence_observations_field_name"), table_name="evidence_observations")
    op.drop_index(
        op.f("ix_evidence_observations_document_revision_id"), table_name="evidence_observations"
    )
    op.drop_table("evidence_observations")
    op.drop_index(op.f("ix_quantities_status"), table_name="quantities")
    op.drop_index(op.f("ix_quantities_boq_line_id"), table_name="quantities")
    op.drop_table("quantities")
    op.drop_index(op.f("ix_normalized_prices_quote_id"), table_name="normalized_prices")
    op.drop_table("normalized_prices")
    op.drop_index(op.f("ix_document_set_revisions_status"), table_name="document_set_revisions")
    op.drop_index(op.f("ix_document_set_revisions_project_id"), table_name="document_set_revisions")
    op.drop_table("document_set_revisions")
    op.drop_index(op.f("ix_document_revisions_object_hash"), table_name="document_revisions")
    op.drop_index(op.f("ix_document_revisions_document_id"), table_name="document_revisions")
    op.drop_table("document_revisions")
    op.drop_index(op.f("ix_calculation_snapshots_project_id"), table_name="calculation_snapshots")
    op.drop_table("calculation_snapshots")
    op.drop_index(op.f("ix_atomic_cost_inputs_project_id"), table_name="atomic_cost_inputs")
    op.drop_index(op.f("ix_atomic_cost_inputs_calculation_run_id"), table_name="atomic_cost_inputs")
    op.drop_table("atomic_cost_inputs")
    op.drop_index(op.f("ix_approval_records_task_id"), table_name="approval_records")
    op.drop_table("approval_records")
    op.drop_index(op.f("ix_workflow_transitions_project_id"), table_name="workflow_transitions")
    op.drop_table("workflow_transitions")
    op.drop_index(op.f("ix_verification_findings_resolved"), table_name="verification_findings")
    op.drop_index(op.f("ix_verification_findings_project_id"), table_name="verification_findings")
    op.drop_index(op.f("ix_verification_findings_contour"), table_name="verification_findings")
    op.drop_index(op.f("ix_verification_findings_code"), table_name="verification_findings")
    op.drop_table("verification_findings")
    op.drop_index(op.f("ix_scope_findings_resolved"), table_name="scope_findings")
    op.drop_index(op.f("ix_scope_findings_project_id"), table_name="scope_findings")
    op.drop_table("scope_findings")
    op.drop_table("project_controlled_versions")
    op.drop_index(op.f("ix_price_quotes_status"), table_name="price_quotes")
    op.drop_index(op.f("ix_price_quotes_project_id"), table_name="price_quotes")
    op.drop_index(op.f("ix_price_quotes_item_id"), table_name="price_quotes")
    op.drop_table("price_quotes")
    op.drop_index(op.f("ix_nomenclature_matches_project_id"), table_name="nomenclature_matches")
    op.drop_index(op.f("ix_nomenclature_matches_match_class"), table_name="nomenclature_matches")
    op.drop_table("nomenclature_matches")
    op.drop_index(op.f("ix_manual_changes_project_id"), table_name="manual_changes")
    op.drop_index(op.f("ix_manual_changes_critical"), table_name="manual_changes")
    op.drop_table("manual_changes")
    op.drop_index(op.f("ix_documents_project_id"), table_name="documents")
    op.drop_table("documents")
    op.drop_index(op.f("ix_conflicts_status"), table_name="conflicts")
    op.drop_index(op.f("ix_conflicts_project_id"), table_name="conflicts")
    op.drop_table("conflicts")
    op.drop_index(op.f("ix_calculation_runs_project_id"), table_name="calculation_runs")
    op.drop_table("calculation_runs")
    op.drop_index(op.f("ix_boq_lines_work_code"), table_name="boq_lines")
    op.drop_index(op.f("ix_boq_lines_wbs_node_id"), table_name="boq_lines")
    op.drop_index(op.f("ix_boq_lines_project_id"), table_name="boq_lines")
    op.drop_table("boq_lines")
    op.drop_index(op.f("ix_approval_tasks_status"), table_name="approval_tasks")
    op.drop_index(op.f("ix_approval_tasks_project_id"), table_name="approval_tasks")
    op.drop_table("approval_tasks")
    op.drop_index(op.f("ix_projects_organization_id"), table_name="projects")
    op.drop_table("projects")
    op.drop_index(op.f("ix_outbox_events_topic"), table_name="outbox_events")
    op.drop_table("outbox_events")
    op.drop_index(op.f("ix_controlled_versions_kind"), table_name="controlled_versions")
    op.drop_table("controlled_versions")
    op.drop_index("ix_audit_aggregate_sequence", table_name="audit_events")
    op.drop_table("audit_events")
    # ### end Alembic commands ###
